# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node

name: CI
on:
  push:
    branches: ['development']
jobs:
  build:
    runs-on: ubuntu-latest

    name: Build on Node 18.12.1 and ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node.js 18.12.1
        uses: actions/setup-node@v3
        with:
          node-version: 18.12.1

      - name: Install deps
        run: yarn install
